### ISSUE TITLE
Unable to download Panoflow pretrained model 

### ISSUE THREAD

**Issue by Sohamsingh2002** [Akaneqwq/360DVD#12]
The provided link for Panoflow pretrained model  requires Wechat/QQ account login to download it which i am unable to make.Could you please make it available to download via google drive link .Thanks in advance.

**Comment by Akaneqwq** [comment]
Thank you for your interest in our project. We have uploaded a copy of  Panoflow pretrained model to Google Drive. You can download it using the following link: [Panoflow Pretrained Model on Google Drive](https://drive.google.com/file/d/1IFhFyohV_7TYRKqAzYTx1EbgYEmZYodA/view).
