### ISSUE TITLE
When will the source code and data could be released?

### ISSUE THREAD

**Issue by WuTao-CS** [Akaneqwq/360DVD#3]
Hello! I am very interested in your impressive and amazing work!
I wonder when will you release your source code and datasets.
If the code is not convenient to open source due to publication issues, can the dataset be made public first?

Thank you!

**Comment by Akaneqwq** [comment]
Thank you for your interest in our work. We will release the dataset within two weeks. The code and weights will be made available after the peer review.

**Comment by WuTao-CS** [comment]
> Thank you for your interest in our work. We will release the dataset within two weeks. The code and weights will be made available after the peer review.

Thank you for your reply!  Looking forward to the dataset being open！

**Comment by PHOENIXFURY007** [comment]
Any updates on the code release? Thanks :)

**Comment by DwanZhang-AI** [comment]
Any updates on the code release? Thanks :)

**Comment by liangbingzhao** [comment]
Any updates on the code release? Thanks :)

**Comment by Akaneqwq** [comment]
Sorry to delay the open-sourcing because of busy. The WEB360 dataset is now available at https://drive.google.com/file/d/1W1eLmaP16GZOeisAR1q-y9JYP9gT1CRs.
