### ISSUE TITLE
Release of codebase ? Expected dates of release. 

### ISSUE THREAD

**Issue by PHOENIXFURY007** [Akaneqwq/360DVD#8]
Congrats on getting accepted to CVPR 2024 !
Can you mention expected timeline for release of code ?

**Comment by Akaneqwq** [comment]
Thank you for your attention! While we cannot provide a precise release date right now, we are aiming to have code and weights available within this month.

**Comment by PHOENIXFURY007** [comment]
Any updates on the code release ?

**Comment by zhanghongyong123456** [comment]
> Any updates on the code release ?

Any updates on the code release ?
